#!/usr/bin/env nix-shell
#!nix-shell -i python3 -p "python3.withPackages(ps: with ps; [ semver githubkit ])"
import os
import subprocess
import json
import time
import textwrap
from pathlib import Path

import semver
from githubkit import GitHub

# Note: for the time being all PRs target master, but this is configurable should the need arise to target eg staging.
TARGET_BRANCH = "master"
BOT_USER = "botnk"
BOT_EMAIL = "github-botnk@korz.dev"

PACKAGE = os.environ["PACKAGE"]
PRE_VERSION = os.environ["PRE_VERSION"]
GH_TOKEN = os.environ["GH_TOKEN"]
GITHUB_WORKFLOW_URL = os.environ.get("GITHUB_WORKFLOW_URL", "")


def cmd(*args, **kwargs):
    return (
        subprocess.check_output(args, stderr=subprocess.STDOUT, **kwargs)
        .decode()
        .strip()
    )


def git_diff_index_clean() -> bool:
    return subprocess.call("git", "diff-index", "--quiet", "HEAD", "--") == 0


def nix_instantiate_eval(expr: str):
    out = cmd(
        "nix-instantiate", "--eval", "-E", "with import ./. {}; " + expr, "--json"
    )
    return json.loads(out)


def get_new_version() -> str:
    return nix_instantiate_eval(f"lib.getVersion {PACKAGE}")


def get_changelog() -> str:
    return nix_instantiate_eval(f"{PACKAGE}.meta.changelog")


def semver_is_upgrade(old, new):
    return semver.compare(new, old) == 1


def search_existing_prs(gh: GitHub, package: str, newversion: str):
    resp = gh.rest.search.issues_and_pull_requests(
        q=f"{package} {newversion} org:NixOS repo:nixpkgs type:pr state:open in:title"
    )
    resp.raise_for_status()
    return resp.parsed_data


def set_git_config():
    cmd("git", "config", "--global", "user.email", BOT_EMAIL)
    cmd("git", "config", "--global", "user.name", BOT_USER)


def fetch_treeless_history(target_branch):
    cmd("git", "fetch", "--refetch", "--filter=tree:0", "origin", target_branch)


def create_and_switch_branch(branch):
    # Checkout the target branch first so that our commit has the right parent.
    cmd("git", "switch", TARGET_BRANCH)
    cmd("git", "switch", "-c", branch)


def git_add_commit(msg):
    cmd("git", "add", ".")
    cmd("git", "commit", "-m", msg)


def git_push(branch):
    remote_url = f"https://{BOT_USER}:{GH_TOKEN}@github.com/{BOT_USER}/nixpkgs.git"
    cmd("git", "push", "--set-upstream", remote_url, branch)


def nix_build(package):
    try:
        output = cmd("nix-build", "-A", package)
        return True, output
    except subprocess.CalledProcessError as e:
        return False, e.output.decode()


def main():
    # Check that there's a diff from the updater script. See https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes.
    if git_diff_index_clean():
        print("No diff after running updater.")
        return

    newversion = get_new_version()
    changelog = get_changelog()

    # Sometimes there's a diff but the version is still the same. For example this
    # happens when the hash has been changed to be in SRI format. In other cases you
    # can even get downgrade suggestions as in https://github.com/NixOS/nixpkgs/pull/197638.
    if not semver_is_upgrade(PRE_VERSION, newversion):
        print(f"{newversion} does not appear to be an upgrade from {PRE_VERSION}")
        return

    print(f"Updating {PACKAGE} from {PRE_VERSION} to {newversion}")

    gh = GitHub(GH_TOKEN)

    # Search to see if someone already created a PR for this version of the package.
    prs = search_existing_prs(gh, PACKAGE, newversion)
    prs_count = prs.total_count
    if prs_count > 0:
        print("There seems to be an existing PR for this change already:")
        for item in prs.items:
            print(item.pull_request.html_url)
        return

    # We need to set up our git user config in order to commit.
    set_git_config()

    # We need to get a complete unshallow checkout if we're going to push to another
    # repo. See https://github.community/t/automating-push-to-public-repo/17742/11?u=samuela
    # and https://stackoverflow.com/questions/28983842/remote-rejected-shallow-update-not-allowed-after-changing-git-remote-url.
    # We start with only a shallow clone because it's far, far faster and it most
    # cases we don't ever need to push anything.
    fetch_treeless_history(TARGET_BRANCH)

    timestamp = int(time.time())
    branch = f"upkeep-bot/{PACKAGE}-{newversion}-{timestamp}"
    create_and_switch_branch(branch)

    commit_msg = f"{PACKAGE}: {PRE_VERSION} -> {newversion}\n\nChangelog: {changelog}"
    git_add_commit(commit_msg)
    git_push(branch)

    # Compose PR body
    template_path = Path(".github/PULL_REQUEST_TEMPLATE.md")
    pr_template = template_path.read_text()
    body = textwrap.dedent(f"""
        Upgrades {PACKAGE} from {PRE_VERSION} to {newversion}

        This PR was automatically generated by [nixpkgs-upkeep](https://github.com/niklaskorz/nixpkgs-upkeep).

        - Changelog: {changelog}
        - [CI workflow]({GITHUB_WORKFLOW_URL}) that created this PR.

        cc @niklaskorz

        <!-- BEGIN_TEMPLATE -->
    """)

    print("Creating a new draft PR on NixOS/nixpkgs...")
    resp = gh.rest.pulls.create(
        owner="NixOS",
        repo="nixpkgs",
        head=f"{BOT_USER}:{branch}",
        base=TARGET_BRANCH,
        title=f"{PACKAGE}: {PRE_VERSION} -> {newversion}",
        body=body + pr_template,
        maintainer_can_modify=True,
        draft=True,
    )
    resp.raise_for_status()
    new_pr = resp.parsed_data
    pr_url = new_pr.html_url
    print(f"Created PR: {pr_url}")

    print("Running nix-build...")
    build_succeeded, build_log = nix_build(PACKAGE)

    if build_succeeded:
        body = (
            "nix-build was successful! Marking this PR as ready for review.\n\n"
            "<details>\n<summary>Complete build log</summary>\n\n"
            "```\n"
            f"> nix-build -A {PACKAGE}\n{build_log}\n"
            "```\n"
            "</details>\n"
        )
        gh.rest.issues.create_comment(
            owner="NixOS",
            repo="nixpkgs",
            issue_number=new_pr.number,
            body=body,
        )
        gh.rest.pulls.update(
            owner="NixOS",
            repo="nixpkgs",
            pull_number=new_pr.number,
            draft=False,
        )
        gh.graphql(
            """
            mutation MarkPullRequestReadyForReview($pr: ID!) {
                markPullRequestReadyForReview(input: { pullRequestId: $pr }) {
                    clientMutationId
                }
            }
            """,
            {"pr": new_pr.id},
        )

        # TODO: run nixpkgs-review as well if nix-build succeeds
    else:
        abbreviated = "\n".join(build_log.splitlines()[-15:])
        body = (
            "nix-build failed. Leaving this PR as a draft for now. Push commits "
            'to this branch and mark as "ready for review" once the build issues have been resolved.\n\n'
            "Abbreviated log:\n"
            "```\n"
            f"> nix-build -A {PACKAGE}\n...\n{abbreviated}\n"
            "```\n\n"
            "<details>\n<summary>Complete build log</summary>\n\n"
            "```\n"
            f"> nix-build -A {PACKAGE}\n{build_log}\n"
            "```\n"
            "</details>\n"
        )
        gh.rest.issues.create_comment(
            owner="NixOS",
            repo="nixpkgs",
            issue_number=new_pr.number,
            body=body,
        )


if __name__ == "__main__":
    main()
