#!/usr/bin/env nix-shell
#!nix-shell -i bash -p curl gh jq semver-tool

set -eou pipefail

# Note: for the time being all PRs target master, but this is configurable should the need arise to target eg staging.
TARGET_BRANCH="master"
BOT_USER="botnk"
BOT_EMAIL="github-botnk@korz.dev"

# Check that there's a diff from the updater script. See https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes.
if git diff-index --quiet HEAD --; then
    echo "No diff after running updater."
    exit 0
fi

newversion="$(nix-instantiate --eval -E "with import ./. {}; lib.getVersion $PACKAGE" --json | jq -r)"
changelog="$(nix-instantiate --eval -E "with import ./. {}; $PACKAGE.meta.changelog" --json | jq -r)"

# Sometimes there's a diff but the version is still the same. For example this
# happens when the hash has been changed to be in SRI format. In other cases you
# can even get downgrade suggestions as in https://github.com/NixOS/nixpkgs/pull/197638.
if [[ $(semver compare "$PRE_VERSION" "$newversion") != "-1" ]]; then
    echo "$newversion does not appear to be an upgrade from $PRE_VERSION"
    exit 0
fi

echo "Updating $PACKAGE from version $PRE_VERSION to version $newversion"

# Search to see if someone already created a PR for this version of the package.
existing_prs=$(curl --silent --get -H "Accept: application/vnd.github.v3+json" --data-urlencode "q=$PACKAGE $newversion org:NixOS repo:nixpkgs type:pr state:open in:title" https://api.github.com/search/issues)
existing_prs_count=$(echo "$existing_prs" | jq .total_count)
if [ "$existing_prs_count" -gt 0 ]; then
    echo "There seems to be an existing PR for this change already:"
    echo "$existing_prs" | jq .items[].pull_request.html_url
    exit 0
fi

# We need to set up our git user config in order to commit.
git config --global user.email "$BOT_EMAIL"
git config --global user.name "$BOT_USER"

# We need to get a complete unshallow checkout if we're going to push to another
# repo. See https://github.community/t/automating-push-to-public-repo/17742/11?u=samuela
# and https://stackoverflow.com/questions/28983842/remote-rejected-shallow-update-not-allowed-after-changing-git-remote-url.
# We start with only a shallow clone because it's far, far faster and it most
# cases we don't ever need to push anything.
git fetch --refetch --filter=tree:0 origin "$TARGET_BRANCH"

# Checkout the target branch first so that our commit has the right parent.
git switch "$TARGET_BRANCH"

# See https://serverfault.com/questions/151109/how-do-i-get-the-current-unix-time-in-milliseconds-in-bash.
branch="upkeep-bot/$PACKAGE-$newversion-$(date +%s)"
git switch -c "$branch"
git add .
git commit -m "$PACKAGE: $PRE_VERSION -> $newversion\n\nChangelog: $changelog"
git push --set-upstream "https://$BOT_USER:$GH_TOKEN@github.com/$BOT_USER/nixpkgs.git" "$branch"

body="Upgrades ${PACKAGE} from ${PRE_VERSION} to ${newversion}

This PR was automatically generated by [nixpkgs-upkeep](https://github.com/niklaskorz/nixpkgs-upkeep).

- Changelog: $changelog
- [CI workflow](${GITHUB_WORKFLOW_URL}) that created this PR.

cc @niklaskorz

$(cat .github/PULL_REQUEST_TEMPLATE.md)"

echo "Creating a new draft PR on NixOS/nixpkgs..."
# For some reason specifying the repo works and is necessary for `--head` but is not accepted by `--base`. Instead we
# specify `--repo` just to be explicit.
pr_url=$(gh pr create \
    --repo "NixOS/nixpkgs" \
    --head "$BOT_USER:$branch" \
    --base "$TARGET_BRANCH" \
    --title "$PACKAGE: $PRE_VERSION -> $newversion" \
    --body "$body" \
    --draft)
echo "Created PR: $pr_url"

echo "Running nix-build..."
if build_log=$(nix-build -A "$PACKAGE" 2>&1); then
    # Use --body-file to work around "Argument list too long" errors.
    body_file=$(mktemp)

    cat <<-_EOM_ > "$body_file"
nix-build was successful! Marking this PR as ready for review.

<details>
<summary>Complete build log</summary>

\`\`\`
> nix-build -A ${PACKAGE}
${build_log}
\`\`\`
</details>
_EOM_

    gh pr comment "$pr_url" --body-file "$body_file"
    gh pr ready "$pr_url"
    rm -f "$body_file"
else
    abbreviated_build_log=$(tail -n15 < "$build_log")
    body_file=$(mktemp)
    cat <<-_EOM_ > "$body_file"
nix-build failed. Leaving this PR as a draft for now. Push commits to this branch and mark as "ready for review" once
the build issues have been resolved.

Abbreviated log:
\`\`\`
> nix-build -A ${PACKAGE}
...
${abbreviated_build_log}
\`\`\`

<details>
<summary>Complete build log</summary>

\`\`\`
> nix-build -A ${PACKAGE}
${build_log}
\`\`\`
</details>
_EOM_

    gh pr comment "$pr_url" --body-file "$body_file"
    rm -f "$body_file"
fi

# TODO: run nixpkgs-review as well if nix-build succeeds
