name: update
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-package:
    strategy:
      fail-fast: false
      matrix:
        package:
          - zed-editor
          - shader-slang
          - ente-auth
    name: ${{ matrix.package }}
    runs-on: ubuntu-latest
    steps:
      - name: Maximize disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
      - run: lscpu
      - uses: "cachix/install-nix-action@v31"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Checkout nixpkgs-upkeep
        uses: "actions/checkout@v4"
        with:
          path: nixpkgs-upkeep
      - name: Checkout nixpkgs
        uses: "actions/checkout@v4"
        with:
          path: nixpkgs
          repository: NixOS/nixpkgs
          token: "${{ secrets.GH_TOKEN }}"
      - name: Check current package version and run update script
        run: |
          PRE_VERSION="$(nix eval --raw --file . ${{ matrix.package }}.version)"
          echo "Current version: $PRE_VERSION"
          echo "PRE_VERSION=$PRE_VERSION" >> $GITHUB_ENV
          nix-shell maintainers/scripts/update.nix --argstr package "${{ matrix.package }}" --argstr skip-prompt true
        working-directory: "./nixpkgs"
      - run: git diff
        working-directory: "./nixpkgs"
      - env:
          GH_TOKEN: "${{ secrets.GH_TOKEN }}"
        name: Create PR
        run: |
          GH_TOKEN="$GH_TOKEN" \
            PACKAGE="${{ matrix.package }}" \
            PRE_VERSION="$PRE_VERSION" \
            GITHUB_WORKFLOW_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" \
            GITHUB_ENV="$GITHUB_ENV" \
            ./../nixpkgs-upkeep/create-pr.py
        working-directory: "./nixpkgs"
      - name: nixpkgs-review
        working-directory: "./nixpkgs"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
        run: |
          if [ "$NIXPKGS_PR_ID" ]; then
            nix-shell -p nixpkgs-review --run "nixpkgs-review pr --no-shell --checkout commit --post-result $NIXPKGS_PR_ID"
          fi
